#!/bin/bash

RED='\033[0;31m'
NC='\033[0m'

echo -e "${RED}Proses menghancurkan Data - Data${NC}"

sleep 10

echo -e "${RED}Menghapus file-file penting...${NC}"

sleep 2
echo "Menghapus ~/Android"
sleep 2
echo "Menghapus ~/DCIM"
sleep 2

# Pesan akhir
sleep 10
echo -e "${RED}Data - Data berhasil dihancurkan!${NC}"

# Logout dari shell
sleep 2
echo "Berhasil"
logout
